// Tamil Nadu constituencies by district/city
export const constituenciesByCity: Record<string, string[]> = {
  'Chennai / சென்னை': [
    'Alandur / ஆலந்தூர்',
    'Ambattur / அம்பத்தூர்',
    'Anna Nagar / அண்ணா நகர்',
    'Chepauk-Thiruvallikeni / சேப்பாக்கம்-திருவல்லிக்கேணி',
    'Egmore / எழும்பூர்',
    'Harbour / துறைமுகம்',
    'Kolathur / கொளத்தூர்',
    'Mylapore / மயிலாப்பூர்',
    'Perambur / பெரம்பூர்',
    'Royapuram / இராயபுரம்',
    'Sholinganallur / சோழிங்கநல்லூர்',
    'Sriperumbudur / ஸ்ரீபெரும்புதூர்',
    'T.Nagar / தியாகராய நகர்',
    'Thiru-Vi-Ka-Nagar / திரு.வி.க நகர்',
    'Thousand Lights / ஆயிரம் விளக்கு',
    'Velachery / வேளச்சேரி',
    'Villivakkam / வில்லிவாக்கம்',
    'Virugambakkam / விருகம்பாக்கம்',
  ],
  'Coimbatore / கோயம்புத்தூர்': [
    'Coimbatore North / கோயம்புத்தூர் வடக்கு',
    'Coimbatore South / கோயம்புத்தூர் தெற்கு',
    'Kinathukadavu / கீனத்துக்கடவு',
    'Mettupalayam / மேட்டுப்பாளையம்',
    'Pollachi / பொள்ளாச்சி',
    'Singanallur / சிங்காநல்லூர்',
    'Sulur / சூலூர்',
    'Thondamuthur / தொண்டாமுத்தூர்',
    'Valparai / வால்பாறை',
  ],
  'Madurai / மதுரை': [
    'Madurai Central / மதுரை மத்தி',
    'Madurai East / மதுரை கிழக்கு',
    'Madurai North / மதுரை வடக்கு',
    'Madurai South / மதுரை தெற்கு',
    'Madurai West / மதுரை மேற்கு',
    'Melur / மேலூர்',
    'Sholavandan / சோளவந்தான்',
    'Thiruparankundram / திருப்பரங்குன்றம்',
    'Usilampatti / உசிலம்பட்டி',
  ],
  'Tiruchirappalli / திருச்சிராப்பள்ளி': [
    'Lalgudi / லால்குடி',
    'Manapparai / மணப்பாறை',
    'Manachanallur / மணச்சநல்லூர்',
    'Musiri / முசிறி',
    'Srirangam / ஸ்ரீரங்கம்',
    'Thiruverumbur / திருவெறும்பூர்',
    'Tiruchirappalli East / திருச்சி கிழக்கு',
    'Tiruchirappalli West / திருச்சி மேற்கு',
    'Thuraiyur / துறையூர்',
  ],
  'Salem / சேலம்': [
    'Attur / ஆத்தூர்',
    'Edappadi / எடப்பாடி',
    'Gangavalli / கங்காவல்லி',
    'Mettur / மேட்டூர்',
    'Omalur / ஓமலூர்',
    'Salem North / சேலம் வடக்கு',
    'Salem South / சேலம் தெற்கு',
    'Salem West / சேலம் மேற்கு',
    'Veerapandi / வீரப்பண்டி',
    'Yercaud / ஏற்காடு',
  ],
  'Tirunelveli / திருநெல்வேலி': [
    'Alangulam / ஆழ்வார்குறிச்சி',
    'Ambasamudram / அம்பாசமுத்திரம்',
    'Nanguneri / நாங்குநேரி',
    'Palayamkottai / பாளையங்கோட்டை',
    'Radhapuram / இராதாபுரம்',
    'Tirunelveli / திருநெல்வேலி',
    'Vasudevanallur / வாசுதேவநல்லூர்',
  ],
  'Tiruppur / திருப்பூர்': [
    'Avanashi / அவனாசி',
    'Dharapuram / தாராபுரம்',
    'Kangayam / கங்கயம்',
    'Palladam / பல்லடம்',
    'Tiruppur North / திருப்பூர் வடக்கு',
    'Tiruppur South / திருப்பூர் தெற்கு',
    'Udumalaipettai / உடுமலைப்பேட்டை',
  ],
  'Erode / ஈரோடு': [
    'Anthiyur / ஆண்டியூர்',
    'Bhavani / பவானி',
    'Bhavanisagar / பவானிசாகர்',
    'Erode East / ஈரோடு கிழக்கு',
    'Erode West / ஈரோடு மேற்கு',
    'Gobichettipalayam / கோபிசெட்டிபாளையம்',
    'Modakurichi / மோடக்குறிச்சி',
    'Perundurai / பெருந்துறை',
    'Sathyamangalam / சத்தியமங்கலம்',
  ],
  'Vellore / வேலூர்': [
    'Arakkonam / ஆற்காடு',
    'Arcot / ஆற்காடு',
    'Gudiyatham / குடியாத்தம்',
    'Katpadi / காட்பாடி',
    'Ranipet / ராணிப்பேட்டை',
    'Sholingur / சோளிங்கர்',
    'Vaniyambadi / வாணியம்பாடி',
    'Vellore / வேலூர்',
    'Ambur / ஆம்பூர்',
  ],
  'Thoothukudi / தூத்துக்குடி': [
    'Ettayapuram / எட்டையபுரம்',
    'Kovilpatti / கோவில்பட்டி',
    'Ottapidaram / ஒட்டப்பிடாரம்',
    'Srivaikuntam / ஸ்ரீவைகுண்டம்',
    'Thoothukudi / தூத்துக்குடி',
    'Tiruchendur / திருச்செந்தூர்',
    'Vilathikulam / விளாத்திகுளம்',
  ],
  'Dindigul / திண்டுக்கல்': [
    'Athoor / அத்தூர்',
    'Dindigul / திண்டுக்கல்',
    'Kodaikanal / கொடைக்கானல்',
    'Natham / நத்தம்',
    'Nilakkottai / நிலக்கோட்டை',
    'Oddanchatram / ஒட்டன்சத்திரம்',
    'Palani / பழனி',
    'Vedasandur / வேடசந்தூர்',
  ],
  'Thanjavur / தஞ்சாவூர்': [
    'Kumbakonam / கும்பகோணம்',
    'Orathanadu / ஓரத்தநாடு',
    'Papanasam / பாபநாசம்',
    'Pattukkottai / பட்டுக்கோட்டை',
    'Peravurani / பேராவூரணி',
    'Thanjavur / தஞ்சாவூர்',
    'Thiruvaiyaru / திருவையாறு',
    'Thiruvidaimarudur / திருவிடைமருதூர்',
  ],
  'Nagercoil / நாகர்கோவில்': [
    'Colachel / கொளச்சல்',
    'Kanyakumari / கன்னியாகுமரி',
    'Killiyoor / கிள்ளியூர்',
    'Nagercoil / நாகர்கோவில்',
    'Padmanabhapuram / பத்மநாபபுரம்',
    'Vilavancode / விளவங்கோடு',
  ],
  'Kanchipuram / காஞ்சிபுரம்': [
    'Alandur / ஆலந்தூர்',
    'Chengalpattu / செங்கல்பட்டு',
    'Cheyyur / செய்யூர்',
    'Kanchipuram / காஞ்சிபுரம்',
    'Maduranthakam / மதுராந்தகம்',
    'Madurantakam / மதுராந்தகம்',
    'Tambaram / தாம்பரம்',
    'Thiruporur / திருப்போரூர்',
    'Uthiramerur / உத்திரமேரூர்',
  ],
  'Cuddalore / கடலூர்': [
    'Bhuvanagiri / புவனகிரி',
    'Chidambaram / சிதம்பரம்',
    'Cuddalore / கடலூர்',
    'Kattumannarkoil / கட்டுமன்னார்கோவில்',
    'Kurinjipadi / குறிஞ்சிப்பாடி',
    'Neyveli / நெய்வேலி',
    'Panruti / பண்ருட்டி',
    'Virudhachalam / விருத்தாசலம்',
  ],
  'Karur / கரூர்': [
    'Aravakurichi / அரவக்குறிச்சி',
    'Karur / கரூர்',
    'Krishnarayapuram / கிருஷ்ணராயபுரம்',
    'Kulithalai / குளித்தலை',
  ],
  'Krishnagiri / கிருஷ்ணகிரி': [
    'Bargur / பர்கூர்',
    'Hosur / ஓசூர்',
    'Kaveripattinam / காவேரிப்பட்டினம்',
    'Krishnagiri / கிருஷ்ணகிரி',
    'Shoolagiri / சூளகிரி',
    'Thalli / தள்ளி',
    'Veppanapalli / வேப்பனப்பள்ளி',
  ],
  'Dharmapuri / தர்மபுரி': [
    'Dharmapuri / தர்மபுரி',
    'Harur / அரூர்',
    'Palacode / பாலக்கோடு',
    'Pappireddipatti / பாப்பிரெட்டிப்பட்டி',
    'Pennagaram / பென்னாகரம்',
  ],
  'Namakkal / நாமக்கல்': [
    'Kolli Hills / கொல்லி மலை',
    'Kumarapalayam / குமாரப்பாளையம்',
    'Namakkal / நாமக்கல்',
    'Paramathi Velur / பரமத்தி வேலூர்',
    'Rasipuram / இராசிபுரம்',
    'Senthamangalam / செந்தமங்கலம்',
    'Tiruchengode / திருச்செங்கோடு',
  ],
  'Ariyalur / அரியலூர்': [
    'Ariyalur / அரியலூர்',
    'Jayankondam / ஜெயங்கொண்டம்',
    'Sendurai / சேந்துறை',
    'Udayarpalayam / உடையார்பாளையம்',
  ],
  'Other / மற்றவை': [
    'Other Constituency / மற்ற தொகுதி',
  ],
};

export const getCitiesFromConstituency = (): string[] => {
  return Object.keys(constituenciesByCity);
};

export const getConstituenciesForCity = (city: string): string[] => {
  return constituenciesByCity[city] || [];
};
